---
apiVersion: v1
kind: Pod
metadata:
  name: vpc-finder
spec:
  containers:
  - name: vpc-finder
    command: ["vpcFinder"]
    args: ["http://imdsv1-mock:8080"]
    env:
     - name: NAMESPACE
       valueFrom:
         fieldRef:
           apiVersion: v1
           fieldPath: metadata.namespace
    image: localhost:5000/vpc-finder:latest
  serviceAccount: vpc-finder
  restartPolicy: OnFailure
  hostNetwork: true
---
apiVersion: v1
kind: Pod
metadata:
  name: imdsv1-mock
  labels:
    app: imdsv1-mock
spec:
  containers:
  - name: imdsv1-mock
    command: ["imdsv1Mocker"]
    image: localhost:5000/vpc-finder:latest
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  name: imdsv1-mock
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: imdsv1-mock
  type: ClusterIP
