---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpc-finder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vpc-finder
rules:
  - apiGroups:
    - ""
    resources:
      - configmaps
    verbs:
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vpc-finder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vpc-finder
subjects:
  - kind: ServiceAccount
    name: vpc-finder
